CREATE TABLE Category
(
    ID INT IDENTITY NOT NULL,
    Name VARCHAR NOT NULL,
    Budget DECIMAL NOT NULL
);

CREATE TABLE Transaction
(
    ID INT IDENTITY NOT NULL,
    Name VARCHAR NOT NULL,
    Type ENUM('INCOME', 'EXPENDITURE'),
    Amount DECIMAL
);